### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by unixorn** [ianthehenry/zsh-expander#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license file.

Please add a license file - if you don't have one in mind,  I recommend using [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.

Thanks!

**Comment by ianthehenry** [comment]
@unixorn Sure, done. Also maybe check out https://github.com/ianthehenry/zsh-autoquoter for a much more refined/useful plugin I wrote.

**Comment by unixorn** [comment]
Thanks for letting me know about autoquoter - I'm adding it too
